export const ADD_NEW_INVOICE = 'ADD_NEW_INVOICE';


export const CHANGE_INPUT_VALUE = 'CHANGE_INPUT_VALUE';
export const SET_ADDNEW_ACTIVE = 'SET_ADDNEW_ACTIVE';
export const CANCEL_NEW_INVOICE = 'CANCEL_NEW_INVOICE';
export const SELECT_CUSTOMER = 'SELECT_CUSTOMER';
export const SELECT_PRODUCT = 'SELECT_PRODUCT';
export const SELECT_DISCOUNT = 'SELECT_DISCOUNT';
export const EDIT_CUSTOMER = 'EDIT_CUSTOMER';
export const CHANGE_INPUT_CUSTOMER_VALUE = 'CHANGE_INPUT_CUSTOMER_VALUE';
export const ADD_NEW_CUSTOMER = 'ADD_NEW_CUSTOMER';
export const CUSTOMER_MODAL_SHOW = 'CUSTOMER_MODAL_SHOW';
export const CUSTOMER_MODAL_HIDE = 'CUSTOMER_MODAL_HIDE';
export const CHANGE_INPUT_PRODUCT_VALUE = 'CHANGE_INPUT_PRODUCT_VALUE';
export const ADD_NEW_PRODUCT = 'ADD_NEW_PRODUCT';
export const PRODUCT_MODAL_SHOW = 'PRODUCT_MODAL_SHOW';
export const PRODUCT_MODAL_HIDE = 'PRODUCT_MODAL_HIDE';
export const CHANGE_PRODUCTQUANTITY = 'CHANGE_PRODUCTQUANTITY';
export const CHANGE_INVOICEITEMS_VALUE = 'CHANGE_INVOICEITEMS_VALUE';
export const DELETE_INVOICE = 'DELETE_INVOICE';
export const START_EDITING = 'START_EDITING';
export const FINISH_EDITING = 'FINISH_EDITING';
export const DELETE_CUSTOMER = 'DELETE_CUSTOMER';
export const START_EDITING_CUSTOMER = 'START_EDITING_CUSTOMER';
export const FINISH_EDITING_CUSTOMER = 'FINISH_EDITING_CUSTOMER';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const START_EDITING_PRODUCT = 'START_EDITING_PRODUCT';
export const FINISH_EDITING_PRODUCT  = 'FINISH_EDITING_PRODUCT';
export const INVOICE_MODAL_SHOW = 'PRODUCT_INVOICE_SHOW';
export const INVOICE_MODAL_HIDE = 'PRODUCT_INVOICE_HIDE';

export const IS_INVOICE_MENU = 'IS_INVOICE_MENU';

/**CUSTOMERS*/
export const FETCH_CUSTOMERS_SUCCESSFUL = 'FETCH_CUSTOMERS_SUCCESSFUL';
export const FETCH_DELETE_CUSTOMERS_SUCCESSFUL = 'FETCH_DELETE_CUSTOMERS_SUCCESSFUL';
export const FETCH_PUT_CUSTOMERS_SUCCESSFUL = 'FETCH_PUT_CUSTOMERS_SUCCESSFUL';
export const FETCH_EDIT_CUSTOMERS_SUCCESSFUL = 'FETCH_EDIT_CUSTOMERS_SUCCESSFUL';
/**PRODUCTS*/
export const FETCH_PRODUCTS_SUCCESSFUL = 'FETCH_PRODUCTS_SUCCESSFUL';
export const FETCH_DELETE_PRODUCTS_SUCCESSFUL = 'FETCH_DELETE_PRODUCTS_SUCCESSFUL';
export const FETCH_PUT_PRODUCTS_SUCCESSFUL = 'FETCH_PUT_PRODUCTS_SUCCESSFUL';
export const FETCH_EDIT_PRODUCTS_SUCCESSFUL = 'FETCH_EDIT_PRODUCTS_SUCCESSFUL';
/**INVOICES*/
export const FETCH_INVOICES_SUCCESSFUL = 'FETCH_INVOICES_SUCCESSFUL';
export const FETCH_DELETE_INVOICES_SUCCESSFUL = 'FETCH_DELETE_INVOICES_SUCCESSFUL';
export const FETCH_PUT_INVOICES_SUCCESSFUL = 'FETCH_PUT_INVOICES_SUCCESSFUL';
export const FETCH_EDIT_INVOICES_SUCCESSFUL = 'FETCH_EDIT_INVOICES_SUCCESSFUL';
/**INVOICEDETAILS*/
export const FETCH_INVOICEDETAILS_SUCCESSFUL = 'FETCH_INVOICEDETAILS_SUCCESSFUL';
export const FETCH_DELETE_INVOICEDETAILS_SUCCESSFUL = 'FETCH_DELETE_INVOICEDETAILS_SUCCESSFUL';
export const FETCH_PUT_INVOICEDETAILS_SUCCESSFUL = 'FETCH_PUT_INVOICEDETAILS_SUCCESSFUL';
export const FETCH_EDIT_INVOICEDETAILS_SUCCESSFUL = 'FETCH_EDIT_INVOICEDETAILS_SUCCESSFUL';

